site_name: Kubernetes Beginner
site_author: Bhavya Sree Bindela
site_description: >-
  Kubernetes Beginner Tutorial
theme:
  name: material
  custom_dir: material
  features:
    - tabs
plugins:
 - mknotebooks:
    execute: false
markdown_extensions:
  - pymdownx.arithmatex
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.betterem
  - pymdownx.superfences
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html
  - toc:
      toc_depth : "1-1"
extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BhavyaSree
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/bhavyabindela
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bhavyabindela
repo_name: BhavyaSree/PythonClass
repo_url: https://github.com/BhavyaSree/Kubernetes-Beginner
edit_uri: ""
# Page tree
nav:
  - Home: README.md
  - Getting started: 01.introduction.md
  - Concepts: 02.kubernetes-concepts.md
  - yaml file: 03.yaml.md 
  - PODs with yaml: 04.pods-with-yaml.md
  - Controllers: 05.controllers.md
  - Deployments: 06.deployments.md
  - Networking: 07.networking.md
  - Services: 08.services.md
  - MicroServices: 09.microservices.md
  - Kubernetes on Cloud: 10.kubernetes-on-cloud.md
  # - Yaml Files:
  #   - Examples:
  #     - POD 1: yaml-files/pod
  #     - POD 2: yaml-files/nginx
  #     - ReplicaSet: yaml-files/replicaset
  #     - Deployment: yaml-files/deployment
  #     - Service : yaml-files/service-definition
  - Help:
    - Documentation: Kubernetes+For+Beginners+-+Mumshad+Mannambeth.pdf
